test one more time

diff --git a/.github/workflows/pre_commit.yml b/.github/workflows/pre_commit.yml
--- a/.github/workflows/pre_commit.yml
+++ b/.github/workflows/pre_commit.yml
@@ -37,7 +37,7 @@ jobs:
         pre-commit install
 
     - name: Run pre-commit
-      run: pre-commit run --all-files || true # `|| true` to not fail when something requires changing
+      run: pre-commit run --all-files # `|| true` to not fail when something requires changing
 
     - name: Determine if changes were made
       id: check_changes
@@ -50,7 +50,7 @@ jobs:
       run: | # `|| true` below to skip if nothing changed from pre-commit
         git config --local user.email "github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
-        git commit -m "pre-commit" -a
+        git commit -m "pre-commit" -a || true
 
     - name: Push changes
       uses: ad-m/github-push-action@v0.8.0
